### ISSUE TITLE
Allow users to mark games as "Favorite"

### ISSUE THREAD

**Issue by vlaminck** [dissolve/PieStation#12]
The ability to mark a game as Favorite would be really nice. 

A game that has been marked as Favorite would have a star next to its name.
Games marked as Favorite would be listed at the top of the game list as well as in place.

It would also be nice, but not necessary, to have a separate top level folder for favorites that contained all the favorites from all the systems.

**Comment by zigurana** [comment]
This is part of the kidmode merge. No stars and indication in the lists though. You can filter the list to show only favs.

**Comment by vlaminck** [comment]
Nice 💯 

Would you like me to create a separate issue for stars next to the names, or is that better suited for the kidmode repo?
